In [2]:
import numpy as np

In [3]:
array = np.array([[1, 2, 3], [2, 3, 4]])

In [4]:
print(array)

[[1 2 3]
 [2 3 4]]


In [5]:
array.all()


True

In [6]:
array.max()


4

In [7]:
a = np.array([10, 20, 30, 40])

In [8]:
b = np.arange(4)

In [9]:
c = a - b

In [11]:
print(b)

[0 1 2 3]


In [12]:
print(a)

[10 20 30 40]


In [13]:
print(c)

[10 19 28 37]


In [14]:
c = b ** 2

In [15]:
print(c)

[0 1 4 9]


In [16]:
c = 10 * np.sin(a)

In [18]:
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [19]:
type(b)

numpy.ndarray

In [20]:
print(b)

[0 1 2 3]


In [21]:
print(b < 3)

[ True  True  True False]


In [22]:
print(b == 3)

[False False False  True]


In [23]:
a = np.array([[1, 2], [0, 1]])

In [24]:
print(a)

[[1 2]
 [0 1]]


In [26]:
b = np.arange(4).reshape((2, 2))  #重新定位成新的维度

In [27]:
print(b)

[[0 1]
 [2 3]]


In [30]:
c = a * b             #矩阵中的元素按位置相乘

In [31]:
print(c)

[[0 2]
 [0 3]]


In [34]:
c_dot = np.dot(a, b)  #矩阵乘法

In [35]:
print(c_dot)

[[4 7]
 [2 3]]


In [36]:
c_dot_2 = a.dot(b)    #另外的一种矩阵相乘写法

In [37]:
print(c_dot_2)

[[4 7]
 [2 3]]


In [40]:
#生成2*4的矩阵，其中每个元素为0~1之前的随机数
a = np.random.random((2, 4))   

In [42]:
print(a)

[[ 0.31016486  0.06928856  0.45089748  0.49489497]
 [ 0.06904683  0.59383332  0.266378    0.23528602]]


In [43]:
#打印所有元素之和
print(np.sum(a))

2.48979004734


In [44]:
#打印元素最小值
print(np.min(a))

0.0690468292773


In [45]:
#打印元素最大值
print(np.max(a))

0.593833320065


In [51]:
# 打印出每行的最小值
print(np.min(a, axis=1))

[ 0.06928856  0.06904683]


In [50]:
# 打印出每列的最小值
print(np.min(a, axis=0))

[ 0.06904683  0.06928856  0.266378    0.23528602]
