In [1]:
import numpy as np

In [2]:
A = np.arange(3, 15)

In [3]:
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
# 打印出下表为3的数值
print(A[3])

6


In [5]:
A = A.reshape(3, 4)

In [6]:
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [8]:
# 此时索引代表行数
print(A[2])

[11 12 13 14]


In [10]:
# 如果要输出8，则要找到8位于第几行第几列
print(A[1][1])

8


In [12]:
# 第二种写法
print(A[1, 1])

8


In [14]:
# 使用冒号来代表所有数：打印第二行的所有数
print(A[2,:])

[11 12 13 14]


In [20]:
# 打印出第二行0~2的所有数，这里冒号右边的数不计入内，输出的数值范围要小1
print(A[2, 0:3])

[11 12 13]


In [27]:
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [31]:
# 按照每一行来进行打印输出
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [32]:
# 要按照每一列来进输出，可以使用转置来进行翻转打印输出(小技巧)
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [35]:
# 将一个矩阵变为一行
print(A.flatten())

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [39]:
# 迭代里面的每一项来进行输出(这里的A.flat是一个迭代器)
for item in A.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


In [40]:
# 或者是
for item in A.flatten():
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14
