In [1]:
import numpy as np

In [3]:
A = np.array([1, 1, 1])

In [4]:
B = np.array([2, 2, 2])

In [5]:
# 上下方式的合并
print(np.vstack((A, B)))

[[1 1 1]
 [2 2 2]]


In [6]:
C = np.vstack((A, B))

In [7]:
print(A.shape, C.shape)

(3,) (2, 3)


In [8]:
# 左右合并
D = np.hstack((A, B))

In [10]:
print(D, D.shape)

[1 1 1 2 2 2] (6,)


In [13]:
# 无法使用装置将一个横向的序列转换成一个纵向的序列
print(A.T)

[1 1 1]


In [16]:
# 在之前加上一个维度(变成一个矩阵)
print(A[np.newaxis, :].shape)

(1, 3)


In [20]:
# 在之后加上一个维度
print(A[ :,np.newaxis].shape)

(3, 1)


In [42]:

B = B[:, np.newaxis]

In [43]:
print(A)
print(B)

[[[1]]

 [[1]]

 [[1]]]
[[[2]]

 [[2]]

 [[2]]]


In [44]:
print(A.T)

[[[1 1 1]]]


In [50]:
C = np.concatenate((A, B), axis=0)

In [51]:
print(C)

[[[1]]

 [[1]]

 [[1]]

 [[2]]

 [[2]]

 [[2]]]
